### ISSUE TITLE
Position of the navigation bar

### ISSUE THREAD

**Issue by Gauravjeetsingh** [amitojsingh/ResponsiveNav#1]
First of all it's position
1) top
2) left

Top navigation
Something like this 
http://responsive-nav.com/

Left navigation
Something like this
http://www.webeffectual.com/

Give your opinion with reason, if top then why, if left then why ?

**Comment by amitojsingh** [comment]
Both are good. 
if we use top navigation then we have to make it responsive on a small screen
but if we use the other one then I don't think their is need to make it responsive as it is already.
and navigation is needed only when we need to navigate not all the time so i will go with Left navigation and moreover it is simple and responsive looks nice and we don't have to make another for the smaller screen.

**Comment by gurjit03** [comment]
yes same point , left navigation is already ready to go ;) whereas top navigation requires efforts to make it responsive.

**Comment by Bravy** [comment]
I agree. I was thinking the same.

**Comment by Gauravjeetsingh** [comment]
I prefer top navigation.
Well I think the only reason if I choose left navigation would be because it requires less effort, which doesn't sound good. It's not the effort that counts, it's the demand of our UI/UX.

Also Left navigation is by nature responsive, and we don't have to do anything to make it responsive.
So I think if we can build a top navigation, then we can easily build left navigation, however I doubt the reverse.

Here's few reasons why both top and left navigation equally score
http://uxmovement.com/navigation/top-navigation-vs-left-navigation-which-works-better/

**Comment by gurjit03** [comment]
From the link - " There are strengths and weaknesses with both top and left navigations. Given these different strengths and weaknesses, this implies that the type of navigation that is best suited for your site is dependent on the type of content your site has."
Here we are not building any site just a navigation bar . But on the other side of the coin , if we try to build  a responsive top nav bar , it would be a good practice for all of us.

**Comment by amitojsingh** [comment]
If we compare both 
according to link:
1st. Scanning
Left: fast as compare to tiles
2. page space 
left : more page space we have
top: less page space
3. Item Priority
In Left all have equal priority 
and In Top priority decreases as we go far.
So i suggest to go with left. 
And if we talk about effort both requires same effort. 
I think top requires less because previously we made top so this we can also But in left Its new for us.

**Comment by Bravy** [comment]
I preffer Left Navigation because the lists are generally easier to scan than tiles, and vertical scrolling is an easy interaction for touchscreen mobile devices.

**Comment by Gauravjeetsingh** [comment]
In a study called Eyetrack III: What We Saw When We Looked Through Their Eyes, results showed that top navigation performed better than left-side navigation

Below is the quote from that study:
“While testing several homepage designs, we varied the placement of a navigation element: top (under the flag or logo), left column, and right column.
“Navigation placed at the top of a homepage performed best — that is, it was seen by the highest percentage of test subjects and looked at for the longest duration.” 

Souce : http://www.smashingmagazine.com/2010/01/11/the-case-against-vertical-navigation/

Having said that, I am not at all against left navigation, I am just curious to know what's the trend in web market, and why is that trend ?
So here's another idea, how about a top navigation for big screens, whereas on mobiles and tablets, that same navigation slides from left. :wink:

**Comment by gurjit03** [comment]
:+1:
