### ISSUE TITLE
Icons for Vertical Bar

### ISSUE THREAD

**Issue by gurjit03** [amitojsingh/ResponsiveNav#10]
Need icons for veritcal menu bar, 3 horizontal vertically above each other and  a cross icon.
The icons should be svg or png.

**Comment by Gauravjeetsingh** [comment]
3 horizontal vertical lines:
http://www.flaticon.com/free-icon/list-menu-three-lines-ios-7-symbol_22238

cross icon:
http://www.flaticon.com/free-icon/cross-out-mark_22108

**Comment by Bravy** [comment]
Check this out 
Horizontal lines
http://www.flaticon.com/free-icon/menu-button-of-three-horizontal-lines_56763

cross icon
http://www.flaticon.com/free-icon/close-cross-circular-interface-button_53639
