### ISSUE TITLE
The logic

### ISSUE THREAD

**Issue by Gauravjeetsingh** [amitojsingh/ResponsiveNav#3]
Logic behind navigation should be discussed here.
How are we gonna make list horizontal for bigger screens and for mobiles as a left navigation

**Comment by Bravy** [comment]
This link was suggested by @gurjit03  http://tympanus.net/Tutorials/ResponsiveRetinaReadyMenu/ 

we can use this in both manners vertical and horizontal

**Comment by Gauravjeetsingh** [comment]
We earlier made a navigation bar, what logic you used to make it responsive ?

Here's mine
I took a unordered list
Using CSS I set the list as horizontal
Gave width 650px to the entire list
And when the browser window size is less than 600px
Then each item of list would have width 100%
And height of navigation is increased from 50px to 250px
Thus our list comes as a vertical list instead of horizontal in case of smaller screens.

**Comment by Gauravjeetsingh** [comment]
Found exactly what we are supposed to make
See this
http://dbushell.github.io/Responsive-Off-Canvas-Menu/step4.html

**Comment by Gauravjeetsingh** [comment]
Complete article of above mentioned demo: http://www.smashingmagazine.com/2013/01/15/off-canvas-navigation-for-responsive-website/

**Comment by gurjit03** [comment]
do we are supposed to build it using css only or can use javascript ?

**Comment by Gauravjeetsingh** [comment]
Only css/scss is better and efficient way I think.

**Comment by gurjit03** [comment]
okk , so no click events then.

**Comment by Gauravjeetsingh** [comment]
Couldn't get you ?
Have you seen the link I shared earlier ?
Any comments on that?

**Comment by gurjit03** [comment]
yaah , that's what i am saying, in your, when we our on mobile view(or shrinking the size of browser) , the icon on clicking show us the off-canvas menu with jquery . But without js we can't apply click events there . Any other logic for it in your mind or just rely on hover event ?

**Comment by Gauravjeetsingh** [comment]
Read this complete article, they first do it with jquery and say it's a bad practice. Then they do the same effect with css.
http://www.smashingmagazine.com/2013/01/15/off-canvas-navigation-for-responsive-website/

We need to get the logic they used for doing it only using css.

**Comment by Gauravjeetsingh** [comment]
Anyone understanding what I want to do ? 
Please ask if any doubt ?

**Comment by gurjit03** [comment]
ohk  , I haven't gone through the complete article . Apologies for that.

**Comment by amitojsingh** [comment]
I got it so lets start. (y)

**Comment by amitojsingh** [comment]
logic kehra labh rahey ho?

**Comment by Gauravjeetsingh** [comment]
Read my previous messages in this issue.
I have shared my logic of how I made simple navigation bar previously when asked.
I want to know the logic of how our this navigation bar would work.

**Comment by gurjit03** [comment]
I have got the trick to open the menu bar with sort of click, but how to close it , is still to be done.

**Comment by Gauravjeetsingh** [comment]
@gurjit03 This issue was to figure out the logic that would turn a horizontal sidebar into a vertical left menu on smaller screens. But I think you started implementing it directly. 

Are you following any tutorial ?
and also explain your problem more clearly, I am unable to understand what's exactly happening.

**Comment by gurjit03** [comment]
Actually , I was trying to solve the problem of how to open that menu bar on click.
For what u are asking, i think it is using javascript ! Just check out that link by shrinking the browser.
