### ISSUE TITLE
push error

### ISSUE THREAD

**Issue by amitojsingh** [amitojsingh/ResponsiveNav#5]
Error wile pushing

To https://github.com/amitojsingh/ResponsiveNav.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/amitojsingh/ResponsiveNav.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Gauravjeetsingh** [comment]
Read the lines that start with hint:
You will get to know what's the problem ?
