### ISSUE TITLE
Make current list horizontal

### ISSUE THREAD

**Issue by Gauravjeetsingh** [amitojsingh/ResponsiveNav#6]
This is simple issue, for now the markup contains a vertical list, all we have to do is to make it horizontal using scss.
This doesn't include any styling, styling will be done later. This issue is just to make the vertical list horizontal.

**Comment by Bravy** [comment]
Done :+1:

**Comment by Gauravjeetsingh** [comment]
With this css, all the lists would become horizontal.
We want only the menu list to be horizontal.
In short instead of li you need to add style to .menu-list > li

Also try to follow same indentation in code, let's keep this code clean.
