### ISSUE TITLE
Mockup of navigation

### ISSUE THREAD

**Issue by Gauravjeetsingh** [amitojsingh/ResponsiveNav#7]
This issue is to style the nav, share your basic idea of how our navigation would look alike
in big screens
in tablets
in phones

It can be a pencil/pen sketch
it can be a rough gimp drawing

Anything would work. I am working on mine, would love to see yours too.

**Comment by amitojsingh** [comment]
check this out. simple and beautiful 
fonts and colour may vary 
![screenshot from 2015-06-05 21 47 47](https://cloud.githubusercontent.com/assets/3595397/8010282/a3217fd4-0bcc-11e5-9985-7bda62980ecf.png)

**Comment by Gauravjeetsingh** [comment]
For bigger screens
![nav1](https://cloud.githubusercontent.com/assets/1990932/8010540/8a79f914-0bce-11e5-8ebb-9986273d5167.png)

For smaller screens
![nav2](https://cloud.githubusercontent.com/assets/1990932/8010541/8a81e2e6-0bce-11e5-9ac5-351f603bcf04.png)

**Comment by Bravy** [comment]
@amitojsingh  dont you think its same as @Gauravjeetsingh show in our 1st issue ??

**Comment by Gauravjeetsingh** [comment]
@Bravy couldn't get you, first issue was for position, this is for it's design.

**Comment by amitojsingh** [comment]
@Gauravjeetsingh  i like your design. its nice :+1:

**Comment by Bravy** [comment]
Let me explain when we were discussing about the position of navigation bar @Gauravjeetsingh gave us a link that was same as @amitojsingh 's design the only difference was in color. @Gauravjeetsingh the logo of Ishwerdas is larger than menu icon. it doesn't look right .

**Comment by Gauravjeetsingh** [comment]
@Bravy I see.
How about this ?
p.s. The boundary is not part of design it's just to outline the design.
![nav2](https://cloud.githubusercontent.com/assets/1990932/8010812/45b2526a-0bd1-11e5-8e74-6d921dd1e696.png)

**Comment by amitojsingh** [comment]
Previous one is better I guess.

**Comment by Bravy** [comment]
Yes previous one was better.

**Comment by Gauravjeetsingh** [comment]
Haha
No worries, we can change it with code afterwards also.
This mockup was just to give rough idea of where should we place what.

**Comment by Bravy** [comment]
http://stuffandnonsense.co.uk/ via @amitojsingh open this link in mobile view. Its really cool.

**Comment by Gauravjeetsingh** [comment]
via @amitojsingh o.O is he with you at your home :stuck_out_tongue:

**Comment by gurjit03** [comment]
sorry for the late contribution actually was working on the logic part. I liked the one shown by Amitoj.

**Comment by Gauravjeetsingh** [comment]
@Bravy The link you suggested is cool but completely different type of navigation, and @gurjit03 has already started working to sort out the logic for the one we decided in first issue, so let's just stick to that.

**Comment by Gauravjeetsingh** [comment]
Navigation for smaller screens
![nav](https://cloud.githubusercontent.com/assets/1990932/8023661/acabf2ac-0d32-11e5-8db7-da51f7191c5c.png)
